#%RAML 0.8
title: simpleapi
version: 1.0
baseUri: http://testspring.cloudhub.io/api
traits:
  - client-id-required:
      queryParameters:
        client_id:
          type: string
          required: true
        client_secret:
          type: string
          required: true
/security:
   get:
      description: some payload
      responses:
       200:
        body:
         text/plain:
/nosecurity:
   get:
      description: some payload
      responses:
       200:
        body:
         text/plain: